### ISSUE TITLE
j-card does not seem to work out of the box.

### ISSUE THREAD

**Issue by Peppe** [jouni/j-elements#1]
I added j-card to my app:
```
<link rel="import" href="../../bower_components/j-elements/j-card.html">
...
<j-card>hello</j-card>
```

Then I checked the browser. J-card did not visually add anything. In the console there's an error:
```
Uncaught TypeError: Vaadin.ThemableMixin is not a function
    at j-card.html:198
    at j-card.html:265
```

and the row 198 is:
```
class CardElement extends Vaadin.ThemableMixin(Polymer.Element) {
```

**Comment by jouni** [comment]
Thanks for the report!

Fixed in 790b262dad2d903a6af98b4b2128db6c301b78f3 and 82018fccee4431d80822b592d29039950b83257f (I had forgotten a bunch of imports).
