### ISSUE TITLE
Drawer: sub-menu solution?

### ISSUE THREAD

**Issue by lkraav** [jouni/j-elements#10]
`<vaadin-tabs>` currently renders top level menu items, but what if sub-menu items are needed, like https://cdn.vaadin.com/vaadin-lumo-styles/1.5.0/demo/icons.html

![image](https://user-images.githubusercontent.com/147228/65670746-a7468b80-e04e-11e9-907f-6cc749006f58.png)

`<vaadin-context-menu>` is the easily available technological choice, but its UX may be suboptimal. For example, if a mobile user taps a collapsed menu item somewhere at the top, context menu suddenly popping up from the bottom seems weird. See screenshot:

![image](https://user-images.githubusercontent.com/147228/65670907-f096db00-e04e-11e9-8252-00907cdb07c1.png)

Your thoughts?

**Comment by jouni** [comment]
I don't think I’ll be working on a navigation component in a while.
