### ISSUE TITLE
Avatar abbreviation font size

### ISSUE THREAD

**Issue by heruan** [jouni/j-elements#2]
The `j-avatar` abbreviation font size adapt to `small` and `large` themes, but if you need a larger (or smaller) avatar and set the width/height explicitly, the abbreviation font size does not adapt.

It would be great to have the abbreviation font size to be relative to the component size.

**Comment by jouni** [comment]
Couldn’t help but try it out 😄  Seems to work nicely!

I’ve been working on the vanilla JS versions of the components, so this enhancement was done in that branch now. I’m still figuring out how to get the new version hosted on GH Pages, so no demo online at the moment.

The relevant parts:
https://github.com/jouni/j-elements/blob/vanilla-js/src/j-avatar.js#L21-L23
https://github.com/jouni/j-elements/blob/vanilla-js/src/j-avatar.js#L8-L13

Feel free to backport it to the Polymer element if you have the time, and send a PR!

**Comment by heruan** [comment]
That's awesome @jouni! I'll try to port this to the Polymer version, but let me say the vanilla JS versions are really intriguing 😃
