### ISSUE TITLE
Consultation project?

### ISSUE THREAD

**Issue by lkraav** [jouni/j-elements#3]
Hi @jouni. I researched j-elements and found them quite intriguing.

Was wondering, are you also available for some independent consulting work, or what would be the best way to work with you? We are thinking about building our web app redesign on Vaadin Web Components, but are new to both Web Components and Vaadin, and would perhaps need occasional guiding and insight into what are optimal solutions in specific scenarios.

Your j-elements repository shows you think in interesting experiments, like us, so it feels like there would be good synergy of competence. Looking forward to hearing back, thanks.

**Comment by jaanmatti** [comment]
Moi Jouni, joining the chat here from Leho's team. Hope all is well. Any idea what would be the best way to add colour values to the template for elements that don't exist in the template right now? Do I just copy-paste an existing element like Success and figure out my own naming pattern?

**Comment by lkraav** [comment]
@jaanmatti this is not the appropriate channel. I informed you about gitter before.
