### ISSUE TITLE
LitElement refactor

### ISSUE THREAD

**Issue by lkraav** [jouni/j-elements#8]
Maybe? :)

**Comment by jouni** [comment]
I would be interested in some, even vague, reasons why it would make sense to convert to LitElement.

My first assumption is that maybe LitElement reduces the amount code needed, making the components better for projects that already include LitElement.

Another assumption is that it could reduce some bugs, as state management would be simplified.

The utilities can’t really be converted. The mixins are not elements, and the other elements are IMO such that they would not really benefit as they contain a bunch of “complex” logic that I’m not sure would translate to lit-html.

**Comment by lkraav** [comment]
> My first assumption is that maybe LitElement reduces the amount code needed, making the components better for projects that already include LitElement.

:arrow_up: mostly this, to start. Further reasoning requires additional evaluation of existing code.

**Comment by jouni** [comment]
I like to keep this research project as close "to the metal" as possible, and I’m not currently considering implementing anything with Lit.
